cat > docker/dovecot/dovecot-ssl.conf << 'EOF'
##
## SSL settings
##

# SSL/TLS support: yes, no, required. <doc/wiki/SSL.txt>
ssl = required

# PEM encoded X.509 SSL/TLS certificate and private key.
ssl_cert = </etc/ssl/certs/dovecot.pem
ssl_key = </etc/ssl/private/dovecot.pem

# If key file is password protected, give the password here. Alternatively
# give it when starting dovecot -p parameter.
#ssl_key_password =

# File containing trusted SSL certificate authorities.
#ssl_ca = 

# Request client to send a certificate. 
#ssl_verify_client_cert = no

# SSL protocols to use
ssl_min_protocol = TLSv1.2

# SSL ciphers to use
ssl_cipher_list = ALL:!LOW:!SSLv2:!EXP:!aNULL

# Prefer the server's order of ciphers over client's.
ssl_prefer_server_ciphers = yes

# SSL extra options. Currently supported options are:
#   no_compression - Disable compression.
#ssl_options = no_compression

# DH parameters length to use.
#ssl_dh_parameters_length = 2048

# SSL protocols to use
ssl_protocols = !SSLv3 !TLSv1 !TLSv1.1

# SSL curve
ssl_curve_list = X25519:secp521r1:secp384r1:prime256v1
EOF