server {

    server_name mongo.infrastructures.help;

    client_max_body_size 100M;

    location / {
        proxy_pass http://localhost:8081;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        
        # Support for MongoDB Express
        proxy_set_header X-Forwarded-Prefix /;
    }

    access_log /var/log/nginx/mongo-express.access.log;
    error_log /var/log/nginx/mongo-express.error.log;

    listen 443 ssl http2; # managed by Certbot
    listen [::]:443 ssl http2;

    ssl_certificate /etc/letsencrypt/live/mongo.infrastructures.help/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/mongo.infrastructures.help/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = mongo.infrastructures.help) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;

    server_name mongo.infrastructures.help;
    return 404; # managed by Certbot


}